name: SAKEC_GATE
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  uuid: ^2.2.0
  image_picker: 0.6.6+5
  image: ^2.1.14
  path_provider: ^1.6.11
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  flutter_spinkit: ^4.1.2+1
  firebase_storage: ^3.1.6
  firebase_messaging: ^5.0.4
  searchable_dropdown: ^1.1.3
  url_launcher: ^5.5.0
  crypt: ^3.0.1
  shared_preferences: ^0.5.12+4
  google_maps_flutter: ^0.4.0
  maps_launcher: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/map.jpg
    - assets/india.png
    - assets/login_page_background.png
    - assets/logo.png
    - assets/sec.png
    - assets/sec1.png
    - assets/staff.png
    - assets/start_page_background.png

  